/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.uoc.mperezma.main;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**  Retrieved via Resources.getColor() and friends. 
         */
        public static final int red=0x7f050000;
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int file=0x7f020001;
        public static final int folder=0x7f020002;
        public static final int geolocator=0x7f020003;
        /**  Retrieved via Resources.getDrawable() and friends. 
         */
        public static final int semi_black=0x7f020004;
    }
    public static final class id {
        public static final int back=0x7f08000d;
        public static final int editor=0x7f08000c;
        public static final int label=0x7f080000;
        public static final int label2=0x7f080003;
        public static final int locationInfo=0x7f080009;
        public static final int mapview=0x7f080008;
        public static final int myGrid=0x7f080007;
        public static final int radio_auto=0x7f080006;
        public static final int radio_blue=0x7f080002;
        public static final int radio_nunca=0x7f080004;
        public static final int radio_red=0x7f080001;
        public static final int radio_siempre=0x7f080005;
        public static final int surface=0x7f08000b;
        public static final int syncLocation=0x7f08000a;
    }
    public static final class layout {
        public static final int config=0x7f030000;
        public static final int gallery=0x7f030001;
        public static final int gugol_map=0x7f030002;
        public static final int image_capture=0x7f030003;
        public static final int list_item=0x7f030004;
        public static final int skeleton_activity=0x7f030005;
        public static final int version=0x7f030006;
    }
    public static final class raw {
        public static final int beep26=0x7f040000;
        public static final int beep29=0x7f040001;
    }
    public static final class string {
        public static final int about=0x7f060024;
        public static final int accept=0x7f06001d;
        public static final int accuracy=0x7f06000a;
        public static final int allways=0x7f060012;
        public static final int altitude=0x7f060007;
        public static final int auto=0x7f060013;
        public static final int back=0x7f060002;
        public static final int bearing=0x7f060009;
        public static final int betaTestTeam=0x7f060016;
        public static final int cancel=0x7f06001e;
        public static final int confirmOverwrite=0x7f06001b;
        public static final int device=0x7f060003;
        public static final int eastDegrees=0x7f06000c;
        public static final int explorer=0x7f06000f;
        public static final int fileSelection=0x7f06000d;
        public static final int flashMode=0x7f060010;
        public static final int gallery=0x7f06000e;
        public static final int gpsUnavailable=0x7f060018;
        public static final int latitude=0x7f060006;
        public static final int longitude=0x7f060005;
        public static final int meters=0x7f06000b;
        public static final int never=0x7f060011;
        public static final int noDigitalCameraImage=0x7f06001f;
        public static final int noGpsInfo=0x7f060019;
        public static final int preferences=0x7f060023;
        public static final int retrievingAddress=0x7f06001a;
        public static final int setImageLocation=0x7f060021;
        public static final int showImageLocation=0x7f060020;
        /**  Simple strings. 
 Simple strings. 
 Simple strings. 
 Simple strings. 
         */
        public static final int skeleton_app=0x7f060000;
        public static final int speed=0x7f060008;
        public static final int syncLocation=0x7f060025;
        public static final int takePicture=0x7f060022;
        public static final int thisAppUsesLibrary=0x7f060017;
        public static final int unavailable=0x7f060004;
        public static final int update=0x7f060001;
        public static final int version=0x7f060015;
        public static final int viewThumbs=0x7f060014;
        public static final int willOverwrite=0x7f06001c;
    }
    public static final class style {
        public static final int ActionButton=0x7f070000;
        public static final int TextAppearance=0x7f070001;
        public static final int TextAppearance_ActionButton=0x7f070002;
    }
}
